language: python

python: 
  - "2.6" 
  - "2.7"
  - "3.2"
  - "3.4" # should work...
  
install:
    - pip install git+https://github.com/NeuralEnsemble/pyelectro.git
    
    - pip install . -r requirements.txt
    
script:
    - pynml -h
    - ./test.sh
    - ls -alt
