
dist: xenial

language: python

addons:
  apt:
    packages:
    - python-matplotlib 

python: 
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  
install:
    #  This requires numpy etc...
    #- pip install git+https://github.com/NeuralEnsemble/pyelectro.git
    
    - pip install .
    
script:
    - pynml -h
    - ./test.sh
    - ls -alt
