name: Ruff
on:
  push:
    branches:
      - master
      - development
      - experimental
      - 'test*'
  pull_request:
    branches:
      - master
      - development
      - experimental
      - 'test*'
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          changed-files: 'true'
